#!/usr/bin/env python3
"""Patch publications.json: fix metadata + fill missing abstracts from cached agent data."""

import json
from pathlib import Path

JSON_PATH = Path(__file__).resolve().parent.parent / "data" / "publications.json"

# ── Fixes ─────────────────────────────────────────────────────────────
FIXES = {
    "MetaOOD": {"year": 2025},
    "Combining Machine Learning Models and Scores using combo Library": {
        "title": "Combining Machine Learning Models using combo Library",
        "id": "workshop-combo",
    },
}

# ── Abstracts from agent results (cached) ─────────────────────────────
ABSTRACTS = {
    "A Survey on LLM-based Conversational User Simulation": "User simulation has long played a vital role in computer science due to its potential to support a wide range of applications. Language, as the primary medium of human communication, forms the foundation of social interaction and behavior. Consequently, simulating conversational behavior has become a key area of study. Recent advancements in large language models (LLMs) have significantly catalyzed progress in this domain by enabling high-fidelity generation of synthetic user conversation. In this paper, we survey recent advancements in LLM-based conversational user simulation. We introduce a novel taxonomy covering user granularity and simulation objectives. Additionally, we systematically analyze core techniques and evaluation methodologies.",
    "DPU: Dynamic Prototype Updating for Multimodal Out-of-Distribution Detection": "Out-of-distribution (OOD) detection is crucial for ensuring the robustness of machine learning models by identifying samples that deviate from the training distribution. While traditional OOD detection has predominantly focused on single-modality inputs, such as images, recent advancements in multimodal models have shown the potential of utilizing multiple modalities to improve detection performance. However, existing approaches often neglect intra-class variability within in-distribution (ID) data. To address this issue, we propose Dynamic Prototype Updating (DPU), a novel plug-and-play framework for multimodal OOD detection that accounts for intra-class variations. Our method dynamically updates class center representations for each class by measuring the variance of similar samples within each batch, enabling tailored adjustments. Extensive experiments on two tasks, five datasets, and nine base OOD algorithms demonstrate that DPU significantly improves OOD detection performances, setting a new state-of-the-art in multimodal OOD detection, including improvements up to 80% in Far-OOD detection.",
    "DyFlow: Dynamic Workflow Framework for Agentic Reasoning": "Agent systems based on large language models (LLMs) have shown great potential in complex reasoning tasks, but building efficient and generalizable workflows remains a major challenge. Most existing approaches rely on manually designed processes, which limits their adaptability across different tasks. To address these limitations, we propose DyFlow, a dynamic workflow generation framework that adaptively constructs and adjusts reasoning procedures based on task requirements and real-time intermediate feedback, thereby enhancing cross-task generalization. DyFlow consists of two core components: a designer and an executor. We systematically evaluate DyFlow across diverse domains, including social reasoning, biomedical tasks, mathematical problem solving, and code generation. Results demonstrate that DyFlow significantly outperforms existing baselines.",
    "JailDAM: Jailbreak Detection with Adaptive Memory for Vision-Language Model": "Multimodal large language models (MLLMs) excel in vision-language tasks but also pose significant risks of generating harmful content, particularly through jailbreak attacks. Detecting such attacks is critical to ensuring the responsible deployment of MLLMs. We introduce JAILDAM, a test-time adaptive framework that leverages a memory-based approach guided by policy-driven unsafe knowledge representations, eliminating the need for explicit exposure to harmful data. By dynamically updating unsafe knowledge during test-time, our framework improves generalization to unseen jailbreak strategies while maintaining efficiency. Experiments on multiple VLM jailbreak benchmarks demonstrate that JAILDAM delivers state-of-the-art performance in harmful content detection.",
    "LLM-Empowered Patient-Provider Communication: A Data-Centric Survey From a Clinical Perspective": "Large language models (LLMs) hold promise for advancing patient-provider communication, yet a persistent gap remains between benchmark-driven model development and the realities of clinical practice. This work presents a systematic, clinically grounded review of text-based medical datasets for LLM training and evaluation. We propose a scenario-based taxonomy derived from established clinical frameworks to map major knowledge-based and conversation-based corpora against core communication scenarios. Our findings highlight the urgent need for scenario-rich datasets and standardized, human-centered evaluation protocol to advance clinically relevant medical LLMs.",
    "Navigating Between Explainability and Extractability in Machine Learning as a Service": "Machine Learning as a Service (MLaaS) systems face a fundamental tension between regulatory demands for explainability and security vulnerabilities from model extraction attacks. This paper advocates for investigating the underexplored relationship between model extractability and explainability. We envision theoretical frameworks enabling MLaaS systems to achieve human-level explainability without enabling extraction attacks. We identify three critical technical gaps: the absence of general frameworks to predict extraction risk, standardized extractability metrics, and predictive security approaches.",
    "Hyperparameter Optimization for Unsupervised Outlier Detection": "Given an unsupervised outlier detection (OD) algorithm, how can we optimize its hyperparameter(s) (HP) on a new dataset, without any labels? In this work, we address this challenging hyperparameter optimization for unsupervised OD problem, and propose the first systematic approach called HPOD that is based on meta-learning. HPOD capitalizes on the prior performance of a large collection of HPs on existing OD benchmark datasets, and transfers this information to enable HP evaluation on a new dataset without labels. Extensive experiments show that HPOD works with both deep and shallow OD algorithms on discrete and continuous HP spaces.",
    "Towards Reproducible, Automated, and Scalable Anomaly Detection": "Anomaly detection (AD), often termed outlier detection, is a key machine learning (ML) task, aiming to identify uncommon yet crucial patterns in data. With the increasing complexity of the modern world, the applications of AD span wide. Here, I will traverse my AD works with promising new directions, particularly emphasizing reproducible benchmarks, automated algorithms, and scalable systems.",
    "TrustLLM: Trustworthiness in Large Language Models": "Large language models (LLMs), exemplified by ChatGPT, have gained considerable attention for their excellent natural language processing capabilities. Nonetheless, these LLMs present many challenges, particularly in the realm of trustworthiness. This paper introduces TrustLLM, a comprehensive study of trustworthiness in LLMs, including principles for different dimensions of trustworthiness, established benchmark, evaluation, and analysis of trustworthiness for mainstream LLMs, and discussion of open challenges and future directions. We first propose a set of principles for trustworthy LLMs that span eight different dimensions. Based on these principles, we further establish a benchmark across six dimensions including truthfulness, safety, fairness, robustness, privacy, and machine ethics.",
    "Do Not Train It: A Linear Neural Architecture Search of Graph Neural Networks": "Neural architecture search (NAS) for Graph neural networks (GNNs), called NAS-GNNs, has achieved significant performance over manually designed GNN architectures. However, these methods inherit issues from the conventional NAS methods, such as high computational cost and optimization difficulty. We derive a novel NAS-GNNs method, namely neural architecture coding (NAC), which holds a no-update scheme on GNNs and can efficiently compute in linear time. Empirical evaluations on multiple GNN benchmark datasets demonstrate state-of-the-art performance.",
    "TOD: GPU-accelerated Outlier Detection via Tensor Operations": "Outlier detection (OD) is a key learning task for finding rare and deviant data samples. In this work, we propose TOD, the first tensor-based system for efficient and scalable outlier detection on distributed multi-GPU machines. A key idea behind TOD is decomposing complex OD applications into a small collection of basic tensor algebra operators. Extensive evaluation on 11 real and 3 synthetic OD datasets shows that TOD is on average 10.9x faster than the leading CPU-based OD system PyOD.",
    "ADBench: Anomaly Detection Benchmark": "Given a long list of anomaly detection algorithms developed in the last few decades, how do they perform with regard to varying levels of supervision, different types of anomalies, and noisy and corrupted data? In this work, we answer these key questions by conducting the most comprehensive anomaly detection benchmark with 30 algorithms on 57 benchmark datasets, named ADBench. Our extensive experiments (98,436 in total) identify meaningful insights into the role of supervision and anomaly types.",
    "BOND: Benchmarking Unsupervised Outlier Node Detection on Static Attributed Graphs": "Detecting which nodes in graphs are outliers is a relatively new machine learning task with numerous applications. We present the first comprehensive benchmark for unsupervised outlier node detection on static attributed graphs called BOND. We benchmark the outlier detection performance of 14 methods ranging from classical matrix factorization to the latest graph neural networks across nine real datasets.",
    "Contrastive Attributed Network Anomaly Detection with Data Augmentation": "Detecting anomalies on attributed networks has a wide spectrum of applications such as spammer detection and fraud detection. We study the novel problem of modeling and integrating human knowledge of different anomaly types for attributed network anomaly detection. We first model prior human knowledge through a novel data augmentation strategy, then integrate the modeled knowledge in a Siamese graph neural network encoder through a well-designed contrastive loss. Experiments on five real-world datasets demonstrate that the proposed framework outperforms the state-of-the-art anomaly detection algorithms.",
    "Automatic Unsupervised Outlier Model Selection": "Given an unsupervised outlier detection task on a new dataset, how can we automatically select a good outlier detection algorithm and its hyperparameter(s)? We tackle the unsupervised outlier model selection (UOMS) problem and propose MetaOD, a principled, data-driven approach to UOMS based on meta-learning. MetaOD capitalizes on the performances of a large body of detection models on historical outlier detection benchmark datasets. Extensive experiments show that selecting a model by MetaOD significantly outperforms no model selection as well as other meta-learning techniques.",
    "Revisiting Time Series Outlier Detection: Definitions and Benchmarks": "Time series outlier detection has been extensively studied with many advanced algorithms. We propose a behavior-driven taxonomy for time series outliers and categorize outliers into point- and pattern-wise outliers with clear context definitions. Following the new taxonomy, we present a general synthetic criterion and generate 35 synthetic datasets. We further identify 4 multivariate real-world datasets from different domains and benchmark 9 algorithms.",
    "SUOD: Accelerating Large-scale Unsupervised Heterogeneous Outlier Detection": "Outlier detection (OD) is a key machine learning task for identifying abnormal objects from general samples. Due to the lack of ground truth labels, practitioners often have to build a large number of unsupervised, heterogeneous models for further combination and analysis. We propose a modular acceleration system, called SUOD, focusing on three complementary acceleration aspects while maintaining performance accuracy. Extensive experiments on more than 20 benchmark datasets demonstrate SUOD's effectiveness.",
    "Therapeutics Data Commons: Machine Learning Datasets and Tasks for Drug Discovery and Development": "Therapeutics machine learning is an emerging field with incredible opportunities for innovation and impact. We introduce Therapeutics Data Commons (TDC), the first unifying platform to systematically access and evaluate machine learning across the entire range of therapeutics. To date, TDC includes 66 AI-ready datasets spread across 22 learning tasks spanning the discovery and development of safe and effective medicines.",
    "A Data Denoising Approach to Optimize Functional Clustering of Single Cell RNA-sequencing Data": "Single cell RNA-sequencing (scRNA-seq) technology enables comprehensive transcriptomic profiling of thousands of cells with distinct phenotypic and physiological states. We developed a novel data denoising and cell clustering approach, namely CIBS, to provide biologically explainable functional classification for scRNA-seq data. Application on two scRNA-seq datasets collected from cancer tumor micro-environment successfully identified subgroups of cancer cells with distinct expression patterns.",
    "AutoAudit: Mining Accounting and Time-Evolving Graphs": "How can we spot money laundering in large-scale graph-like accounting datasets? We propose a flexible system called AutoAudit with four major advantages: Smurfing Detection that spots nearly 100% of injected money laundering transactions, Attention Routing to the most suspicious part of time-evolving graphs, Insight Discovery identifying similar month-pair patterns, and Scalability ensuring linear scaling.",
    "COPOD: Copula-Based Outlier Detection": "Outlier detection refers to the identification of rare items that are deviant from the general data distribution. We present a novel outlier detection algorithm called COPOD, inspired by copulas for modeling multivariate data distribution. COPOD first constructs an empirical copula, and then uses it to predict tail probabilities of each given data point to determine its level of extremeness. COPOD is both parameter-free, highly interpretable, and computationally efficient.",
    "LSCP: Locally Selective Combination in Parallel Outlier Ensembles": "In unsupervised outlier ensembles, the absence of ground truth makes the combination of base outlier detectors a challenging task. We propose LSCP which addresses the issue by defining a local region around a test instance using the consensus of its nearest neighbors in randomly selected feature subspaces. The top-performing base detectors in this local region are selected and combined. Experimental results demonstrate that LSCP_AOM consistently outperforms baselines on the majority of twenty real-world datasets.",
    "Music Artist Classification with Convolutional Recurrent Neural Networks": "This paper revisits artist classification with deep convolutional and recurrent models and empirically explores the impacts of incorporating temporal structure in the feature representation. A Convolutional Recurrent Neural Network (CRNN) is applied to the artist20 music artist identification dataset. The best performing model achieves an average F1 score of 0.937 across three independent trials.",
    "Employee Turnover Prediction with Machine Learning: A Reliable Approach": "Supervised machine learning methods are described, demonstrated and assessed for the prediction of employee turnover within an organization. Numerical experiments for real and simulated human resources datasets are performed using ten different methods. Through a robust and comprehensive evaluation process, the performance of each method is analyzed and established using statistical methods.",
    "XGBOD: Improving Supervised Outlier Detection with Unsupervised Representation Learning": "A new semi-supervised ensemble algorithm called XGBOD (Extreme Gradient Boosting Outlier Detection) is proposed for the enhanced detection of outliers. The proposed framework combines the strengths of both supervised and unsupervised machine learning methods by creating a hybrid approach. XGBOD uses multiple unsupervised outlier mining algorithms to extract useful representations that augment the predictive capabilities of an embedded supervised classifier.",
    "TRUSTEVAL: A Dynamic Evaluation Toolkit on Trustworthiness of Generative Foundation Models": "Ensuring the trustworthiness of Generative Foundation Models (GenFMs) is a pressing challenge as they gain widespread use. This paper introduces TRUSTEVAL, a dynamic and comprehensive toolkit designed for evaluating GenFMs across various dimensions. TRUSTEVAL supports both dynamic dataset generation and evaluation, offering advanced features including comprehensiveness, usability, and flexibility.",
    "TODS: An Automated Time Series Outlier Detection System": "We present TODS, an automated Time Series Outlier Detection System for research and industrial applications. TODS is a highly modular system that supports easy pipeline construction with 70 primitives, including data processing, time series processing, feature analysis, detection algorithms, and a reinforcement module. TODS provides a Graphical User Interface (GUI) and a data-driven searcher to automatically discover the most suitable pipelines.",
    "SynC: A Copula based Framework for Generating Synthetic Data from Aggregated Sources": "We study a specific synthetic data generation task called downscaling, a procedure to infer high-resolution information from many low-resolution easy-to-collect sources, and propose SynC (Synthetic Data Generation via Gaussian Copula). For given low-resolution datasets, SynC fits Gaussian copula models to each dataset to correctly capture dependencies and marginal distributions, and then samples from the fitted models to obtain the desired high-resolution subsets.",
    "LEGO-Learn: Label-Efficient Graph Open-Set Learning": "How can we train graph-based models to recognize unseen classes while keeping labeling costs low? We propose LEGO-Learn (Label-Efficient Graph Open-set Learning), a novel framework that tackles open-set node classification on graphs within a given label budget by selecting the most informative ID nodes. Experimental results on four real-world datasets demonstrate that LEGO-Learn significantly outperforms leading methods.",
    "The Need for Unsupervised Outlier Model Selection: A Review and Evaluation of Internal Evaluation Strategies": "Given an unsupervised outlier detection task, how should one select a detection algorithm and associated hyperparameter values? We first survey internal model evaluation strategies, then investigate their effectiveness empirically. Our study reports a striking finding that none of the existing and adapted strategies would be practically useful. Our survey stresses the importance of and the standing need for effective unsupervised outlier model selection.",
    "Artificial Intelligence Foundation for Therapeutic Science": "Artificial intelligence (AI) is poised to advance therapeutic science. Therapeutics Data Commons is an initiative to access and evaluate AI capability across therapeutic modalities and stages of discovery, establishing the foundation of which AI methods are most suitable and why.",
    "PyOD: A Python Toolbox for Scalable Outlier Detection": "PyOD is an open-source Python toolbox for performing scalable outlier detection on multivariate data. Uniquely, it provides access to a wide range of outlier detection algorithms, including established outlier ensembles and more recent neural network-based approaches, under a single, well-documented API designed for use by both practitioners and researchers.",
    "An Empirical Study of Touch-based Authentication Methods on Smartwatches": "The emergence of smartwatches poses new challenges to information security. We conducted a user study (n=16) to evaluate how authentication methods (PIN and Pattern), UIs (Square and Circular), and display sizes (38mm and 42mm) affect authentication accuracy, speed, and security. Results show that PIN is more accurate and secure than Pattern; Pattern is much faster than PIN; Square UIs are more secure but less accurate than Circular UIs.",
    "SynC: A Unified Framework for Generating Synthetic Population with Gaussian Copula": "Synthetic population generation is the process of combining multiple socioeconomic and demographic datasets from different sources and downscaling them to an individual level. We propose SynC (Synthetic Population via Gaussian Copula), a multi-stage framework that fits filtered data with a Gaussian copula model to correctly capture dependencies and marginal distributions of sampled survey data.",
    "DCSO: Dynamic Combination of Detector Scores for Outlier Ensembles": "Selecting and combining the outlier scores of different base detectors used within outlier ensembles can be quite challenging in the absence of ground truth. We propose DCSO, an unsupervised outlier detector combination framework for the dynamic selection of most competent base detectors, with an emphasis on data locality. Experimental results on ten benchmark datasets demonstrate that DCSO provides consistent performance improvement over existing static combination approaches.",
}


def main():
    with open(JSON_PATH, encoding="utf-8") as f:
        papers = json.load(f)

    # 1. Apply fixes
    for p in papers:
        for key, fix in FIXES.items():
            if key.lower() in p["title"].lower():
                for k, v in fix.items():
                    p[k] = v
                print(f"Fixed: {p['title'][:50]} -> {fix}")

    # 2. Fill abstracts
    filled = 0
    for p in papers:
        if p.get("abstract"):
            continue
        for key, abstract in ABSTRACTS.items():
            if key.lower() in p["title"].lower() or p["title"].lower() in key.lower():
                p["abstract"] = abstract
                filled += 1
                break

    print(f"Filled {filled} abstracts")

    # 3. Check remaining
    still_missing = [p["title"] for p in papers if not p.get("abstract")]
    print(f"Still missing: {len(still_missing)}")
    for t in still_missing:
        print(f"  - {t[:60]}")

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(papers, f, indent=4, ensure_ascii=False)
        f.write("\n")

    total_with = sum(1 for p in papers if p.get("abstract"))
    print(f"\nTotal: {len(papers)} papers, {total_with} with abstracts")


if __name__ == "__main__":
    main()
